- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: build image
      command: "docker build -t {{ image_name }}:{{ tag }} ."

    - name: docker push
      command: "docker push {{ image_name }}:{{ tag }}"
